### ISSUE TITLE
unsubscribe_to

### ISSUE THREAD

**Issue by thiaguerd** [ryanb/private_pub#114]
i need unsubscribe_to or something similar

rb: subscribe_to "/a/b" make
js: PrivatePub.sign({"server":"a","timestamp":0,"channel":"/a/b","signature":"y"});

rb: unsubscribe_to "/a/b" make
js: PrivatePub.signout({"server":"a","timestamp":0,"channel":"/a/b","signature":"y"});

**Comment by Rdbaker** [comment]
https://github.com/ryanb/private_pub/blob/master/app/assets/javascripts/private_pub.js#L82
might be what you're looking for

**Comment by eduardobarbiero** [comment]
Rdbaker, thanks!
This works fine.

**Comment by thiaguerd** [comment]
solved
